db:
  image: postgres
  environment:
    POSTGRES_USER: ${POSTGRE_USER}
    POSTGRES_PASSWORD: ${POSTGRE_PASS}
  volumes:
    - ${VOLUME}:/var/lib/postgresql/data
  restart: always

taigaback:
  image: htdvisser/taiga-back:stable
  environment:
    SECRET_KEY: examplesecretkey
    EMAIL_USE_TLS: 'True'
    EMAIL_HOST: smtp.gmail.com
    EMAIL_PORT: 587
    EMAIL_HOST_USER: youremail@gmail.com
    EMAIL_HOST_PASSWORD: yourpassword
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
  links:
    - db:postgres
  volumes:
    - ${TAIGA_MEDIA_VOL}:/usr/local/taiga/media
    - ${TAIGA_STATIC_VOL}:/usr/local/taiga/static
    - ${TAIGA_LOG_VOL}:/usr/local/taiga/logs
  restart: always

taigafront:
  image: htdvisser/taiga-front-dist:stable
  links:
    - taigaback
  ports:
    - 0.0.0.0:80:80
  restart: always